### ISSUE TITLE
AIVCtrl user interface layout is bad on HiDPI display

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [ptstream/QtUPnP#11]
The icons are tiny which makes it pretty much unusable.

I'm really looking for a full-function uPNP control point, something like the BubbleUPnP app I have on my Android phone, but working on my Pop!_OS (Ubuntu) 18.04 LTS laptop, which has a 15.6 inch 3840×2160 4K HiDPI display.

**Comment by ptstream** [comment]
Hi Bananas-Are-Yello,
I understand your problem.
AIVCtrl has been tested for 800x480 of the Raspberry PI 3 with official touch screen, to 1920x1080 of my laptop and effectively, for you the icons must be very small.
I have no immediate solution to offer you other than rebuild AVICtrl with larger icons.
Sorry.

**Comment by ptstream** [comment]
Hi Bananas-Are-Yello,

I tried a very simple solution to help you.
In Qt designer, you can select all QToolButtons of the mainwindow form (mainwindow.ui).
You can change the size of the QToolButton icons from 32x32 to 48x48 or 64x64.
You rebuild the AIVCtrl project.
I tested this change very rapidly, the different layouts of the main window make the job.

Another solution is to add a small peace of code, in the CMainWindow constructor,  like this (not tested):
```
  QSize size (64, 64)
  QList<QToolButton*> buttons = findChildren<QToolButton*> ();
  for (QToolButton* button : buttons)
  {
    button->setIconSize (size);
  }
```

I will see how to integrate this into the AIVCtrl project. For example, add a capability to choose in different icon size by the user. Save and restore at restart.
It will not be possible immediately because I am working on two other projects that I would like to finish before.

Regards,
Patrice

**Comment by ptstream** [comment]
Hi Bananas-Are-Yello,
You request is planned for the next version (1.1.3) 
Patrice
