### ISSUE TITLE
confirming working device - except track advance

### ISSUE THREAD

**Issue by jdegraef** [ptstream/QtUPnP#12]
I intended to just post a working device, well it almost works, all is fine except for automatic track advance.  I need to manually click the "next" icon to advance to queue.

version 1.1.2 on win10

server: minidlna (on LEDE/OpenWRT)
renderer: GGMM E5 (es-100)

thanks!

**Comment by ptstream** [comment]
hi jdegraef

Many thanks for your precious help.

I'm sorry about the problem of automatic advance. It is, of course, an issue.
But I don't know if it is a problem of AIVCtrl, your GGMM E5, the two.

I will try to analyze the problem but it is very difficult without any other information.
The UPnP protocol, especially in version 1, gives manufacturers a lot of freedom.
So that the implementation may be very different from one device to another.
I tried to take into account particuliarities but I can not buy all the materials :confused: to test them individually.

I don't know if your used AIVCtrl from the installers or if your have build it from the source files.
If your have build it from the source files, probably you can build chupnp. 
chupnp is a program that displays the capabilities of a UPnP compatible devices (and also send manually UPnP actions).
If you have time to send me some results, I could do an in-depth analysis of the UPnP protocol implementated on your GGMM E5.

Thanks again,
Patrice

**Comment by jdegraef** [comment]
Hi Patrice,
i sent you thetwo exports from chupnp.

I just wanted to add i can see the 'stopped' event in the events tab. So at least both players are signalling the end of the track correctly.

**Comment by ptstream** [comment]
Hi jdegraef,

Many thanks for this information.
I checked your files. The problem is simple.

1. urn:schemas-upnp-org:service:ConnectionManager:1
   The results of GetProtocolInfo -> Sink is:
        http-get:*:audio/wav:DLNA.ORG_PN=LPCM
        http-get:*:audio/x-wav:DLNA.ORG_PN=LPCM
        http-get:*:audio/mpeg:DLNA.ORG_PN=MP3
        http-get:*:audio/mpeg:DLNA.ORG_PN=MP3X
        http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMABASE
        http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMAFULL
        http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMAPRO
        http-get:*:audio/mpeg:DLNA.ORG_PN=MP2_MPS
        http-get:*:audio/mp3:*
        http-get:*:audio/wma:*
        http-get:*:audio/mpeg:*
        http-get:*:audio/vnd.dlna.adts:DLNA.ORG_PN=AAC_ADTS
        http-get:*:audio/vnd.dlna.adts:DLNA.ORG_PN=AAC_ADTS_320
        http-get:*:audio/m4a:DLNA.ORG_PN=AAC_ISO
        http-get:*:audio/aac:DLNA.ORG_PN=AAC_ISO
        http-get:*:audio/ac3:DLNA.ORG_PN=AC3
        http-get:*:audio/ogg:*
        http-get:*:audio/ape:*
        http-get:*:audio/x-ape:*
        http-get:*:audio/flac:*
		
   The protocol UPnP/AV implements playlists throw the format http-get:*:audio/x-mpegurl:*
   This format is not implemented in your renderer.
   
2. urn:schemas-upnp-org:service:AVTransport:1
   The protocol UPnP/AV defines another way to implement automatic advance. This is done by the implementation of SetNextAVTransportURI and/or SetNextAVTransportURIMetaData action.
   For your renderer, the variables NextAVTransportURI NextAVTransportURIMetaData are implemented but the above actions not.
   
Remarks:
1. Your renderer mix the standard UPnP/AV variables and actions with manufacturer variables and actions. E.g. variables BateryFlag and BateryPercent
   in AVTransport service. It is not strictly prohibited but without documentation it is not simple to use.

2. Your renderer manage queue, probably, throw urn:schemas-wiimu-com:service:PlayQueue:1.
   Unfortunatly it is not a standard service but a manufacturer service.
   
Conclusion:
To solve your problem, I have to make changes in AIVCtrl. I did not foresee this case.
I note and it will be implemented in the next version.

Thanks again for your help,
Patrice

**Comment by jdegraef** [comment]
hi, yes, the wonderful world of DLNA semi-compliance and allowed vendor-extensions :-/

The GGMM comes with its own app to manage the playlist/queue. I probably could spy the commands of the network if that's the route you intend the follow - but I would advise against it. As you noted it's vendor specific AND the depth is quite limited (16 or so tracks. IIRC) so you'd have to manage a partial playlist on the device which feels like a headache you'd want to avoid.

anyway, thanks again for the quick follow-up, and as mentioned in my mail I've got a couple more DLNA devices I can test with.
jo
