### ISSUE TITLE
Discover finished notification

### ISSUE THREAD

**Issue by steveq61** [ptstream/QtUPnP#5]
Hi,
Perhaps I haven't fully grasped how CControlPoint::discover() works, so I'm sorry if this is a bad question. I would like to get some sort of notification when the discover process is complete.
I am successfully discovering network devices, but I want to know when QtUPnP has stopped looking because they have all been found.
Is there a slot notification for this?
Is this possible please?
Thanks,
Steve Q. :-)

**Comment by ptstream** [comment]
Hi,

I understand your question, but it is not possible to make this.

The UPnP protocol works like this: (big simplification)

1.       A control point sends a set of UDP discovery messages using a multicast address (239.255.255.250).
Normally all UPnP compatibles devices listen this address and  have to send back a response.

2.       The control point waits the response of the devices.  The response delay is extremely variable.
It depends on the network load, the number of compatible devices, the algorithm used by the devices and a lot of other thinks (e.g. the device is not ready to intercept the M-SEARCH message).

In fact, the control point does not know when the devices will respond. This can be between a few seconds and several minutes.
Moreover, some devices can leave the network (turn off or wireless out of reach), some other are turned on  after the discovery message.
The control point always listen for network input or output.

I hope to have been clear
Regards,
Patrice



De : steveq61 [mailto:notifications@github.com]
Envoyé : dimanche 22 avril 2018 10:44
À : ptstream/QtUPnP
Cc : Subscribed
Objet : [ptstream/QtUPnP] Discover finished notification (#5)


Hi,
Perhaps I haven't fully grasped how CControlPoint::discover() works, so I'm sorry if this is a bad question. I would like to get some sort of notification when the discover process is complete.
I am successfully discovering network devices, but I want to know when QtUPnP has stopped looking because they have all been found.
Is there a slot notification for this?
Is this possible please?
Thanks,
Steve Q. :-)

**Comment by steveq61** [comment]
Hey Patrice,
Thanks so much for your prompt reply. To be honest I thought your answer may be along these lines, but I was hoping not. I guess I'll have to look at the way I am structuring my software.
Thank you,

Steve Q. :-)
