### ISSUE TITLE
eventReady Slot

### ISSUE THREAD

**Issue by steveq61** [ptstream/QtUPnP#6]
Hi Again!
I don't seem to be getting any `eventReady `notifications. I set up my control point like this:
```javascript
    m_cp = new CControlPoint( this );

    m_cp->setExpandEmbeddedDevices(); // Put a copy of embedded devices in the device map.

    connect (m_cp, SIGNAL(upnpError(int, QString const &)), this, SLOT(upnpError(int, QString const &)));
    connect (m_cp, SIGNAL(networkError(QString const &, QNetworkReply::NetworkError, QString const &)), this, SLOT(networkError(QString const &, QNetworkReply::NetworkError, QString const &)));
    connect (m_cp, SIGNAL(newDevice(QString const &)), this, SLOT(newDevice(QString const &)));
    connect (m_cp, SIGNAL(eventReady(QStringList const &)), this, SLOT(eventReady(QStringList const &)));
```
In my header file:
```javascript
protected slots :
    void newDevice (QString const & uuid);
    void upnpError (int errorCode, QString const & errorString);
    void networkError (QString const & deviceUUID, QNetworkReply::NetworkError errorCode, QString const & errorString);
    void eventReady (QStringList const & emitter);
```
And finally my slot:
```javascript
void MainWindow::eventReady (QStringList const & emitter)
{
    QMessageBox::information(this, tr("EventReady"), "Notification received." );
}
```
In your test program chupnp, I am getting notification from my upnp devices (wemo switches). But not in my software. Am I doing everything correctly, or am I missing something?

Thanks heaps for your help,

Steve Q. :-)

**Comment by ptstream** [comment]
- It is a method but the function **CControlPoint::subscribe** make this for you. You just pass the uuid of your device (I see in your code, you subscribe at all services that are able to emit events). 

- The control point unsubscribe automaticaly the subscribed services in the destructor.

Patrice

**Comment by steveq61** [comment]
Hey Patrice,
This is now working. Thank you.
One more question though. I seem to be getting several different events from my devices.

- basicevent
- remoteaccess
- WifiSetup
- firmwareupdate

etc...
I am only interested in one of these, `basicevent/BinaryState`. Is there a way to only receive this event, or should I just receive them all and just filter what I don't use?

Thanks so much for your help once again.

SQ :-)

**Comment by ptstream** [comment]
Hi Steve,

**Subscribe at only a subset of device services** 
It is not directly implemented in the library because subscribtion needs to define an http server.
You can check something like that (**not tested**):
<pre>
void validateEventingForOneService (QString const & type)
{
  CDevice& device = m_devices[deviceUUID]; 
  TMServices& services  = device.services (); 
  for (TMServices::iterator it = services.begin (), end = services.end (); it != end; ++it)
  { 
     CService& service = *it;
     if (service.m_serviceType () != type) 
     {
       service.setEvented (false);
     }
  } 
}

// You can call now CControlPoint::subscribe.
// This function checks if the service is valid for eventing.
</pre>

**renewDelay**
The subscribtion is valid for an amount of time. Periodically is it mandatory to renew the subscription. It is to solve the case, for example,  of the control point crash or lost the network. The device musts freed the invalid subscibtion. 

**requestTimeout**
Subscribtion needs an http communication between the control point and the device. Like all http communications, it is necessary to define a timeout of the request in case of the device is stopped (crash, shutdown,...). In most case, the default values are revelant.

**Remark**
I am very suprised by your sentence "**If I receive all of them, it slows my app down considerably, as you say, network traffic is increased.**". Generally for one device, the traffic generated by UPnP eventing  is very weak.

Regards,
Patrice

**Comment by steveq61** [comment]
Hi Patrice,
Thanks heaps, I'll try this code once I get in front of my computer tonight.

With regards to your remark, my app is a simple controller for some light switches and socket switches. I have 15 of them . I'm getting at least 5 events per switch as they are discovered. Consequently the event slot is blocking my gui update, slowing the whole thing down. Hopefully I'll only get the one event I need after I try your code and all will be well! Perhaps I could set a timer of say 10 secs, and not launch the subscription until the timer has expired.

I'll let you know how I get on soon.

Thanks again,

Steve Q. :-)

**Comment by steveq61** [comment]
Hey Patrice,

I'm struggling to get this to compile. I keep getting this error:
```
error: binding 'const QtUPnP::CService' to reference of type 'QtUPnP::CService&' discards qualifiers
             CService& service = *it;
                                  ^
```
My code is as follows:
```javascript
        TMServices const & services = device.services ();

        for (TMServices::const_iterator it = services.begin (), end = services.end (); it != end; ++it)
        {
            CService& service = *it;

            // Just subscribe to the binary state notification
            if ( service.serviceType() != "urn:Belkin:service:basicevent:1" )
            {
                service.setEvented( false );
            }
        }

        m_cp->subscribe( uuid );
```
Note I change the `m_serviceType `to `serviceType()`

SQ :-)

**Comment by ptstream** [comment]
- The problem is probably the using of const objects. **service->setEvented** function cannot work with constant object because it modify the object. In my code I don't use const object.

- When you subscribe at a service, it is normal to receive a lot of events. The protocol UPnP indicates that after subscription, the device must sends the state of all evented state variables. But after this initialisation phase, the number of events are generally very tiny.

Patrice

**Comment by steveq61** [comment]
Hey Patrice,
Yeah I can't seem to get this compiling. Perhaps this is a feature you might consider adding in the next update?
I'll add a one shot timer of about 10 sec as a part of the discover process. Once the timer is called, I'll subscribe. Hopefully that will be long enough for the GUI to update. Then it won't be so noticeable once I do subscribe.
Thanks once again for your advice.

Steve Q. :-)

**Comment by ptstream** [comment]
I don't know what's append. Subscribe at all devices at the same time is a problem, maybe. Try to delayed the different subscriptions.
In all cases, the subscription is not blocking. The UI is updated normally. Just Sockets events and user events are delayed.
Remember also, QT manages network communications throw different threads for each. All is asynchronius and send or receive a lot of network messages at the same time is difficult to manage.

**"The remote host closed the connection"**  means between connection and write data, the device close the connection. It is difficult to analyse the problem without your network.
For the second error means the header of the http message is wrong and the device don't understand this header.

Patrice

**Comment by steveq61** [comment]
I have just fixed this issue.

```javascript
    struct WemoSwitch *ws;

    QVariant variant;

    foreach( QVBoxLayout *vlay, m_buttonArray )
    {
        variant = vlay->property("WemoSwitch");

        ws = variant.value<WemoSwitch *>();

        m_cp->subscribe(ws->UUID);

        qApp->processEvents();
    }
```

As you can see I've added a `qApp->processEvents();` at the bottom of the loop . It seems to have solved the problem.

Can I be a pain and ask one more question please. If I know the IP address and port of my device, is it possible to provide that to a `CControlPoint `and have it create the device and return the UUID or an error if is does not exist?
I'm just trying to avoid `discover` as much as I can. If there is an error returned (ie DHCP has refreshed the devices IP address etc), then I can do a `discover`.

Sorry for the many questions!

SQ :-)

**Comment by ptstream** [comment]
Hi Steve,
It is probably possible to manually add a device to the control point but this is far from the UPnP protocol.
Moreover in this case, a device can be detected as good but it will not be the right device. Nothing in the UPnP protocol specifies that the uuid must be unique in time. I have the case of a modem that changes uuid at each reboot.
Regards,
Patrice
